### ISSUE TITLE
compilation error when compiling the include example

### ISSUE THREAD

**Issue by mcousine** [Seeed-Studio/RFID_Library#1]
RFID_UART:12: error: 'SeeedRFID' does not name a type
RFID_UART:13: error: 'RFIDdata' does not name a type
RFID_UART.ino: In function 'void loop()':
RFID_UART:21: error: 'RFID' was not declared in this scope
RFID_UART:22: error: 'tag' was not declared in this scope

**Comment by mcousine** [comment]
Should be quote not <<
#include "SoftwareSerial.h"
#include "SeeedRFID.h"

not 

#include <<>>
#include <<SeeedRFID.h>>

i'm new in the include but if you place de comma it's search into the directory which is less error prone for newbies.... like me

**Comment by yexiaobo-seeedstudio** [comment]
I put my code to `Arduino/libraries`, so it's not problem when `include <SeeedRFID.h>` :smile:
