### ISSUE TITLE
antenna reading range

### ISSUE THREAD

**Issue by neurochill** [Seeed-Studio/RFID_Library#11]
I recently purchased a Grove 125kHz reader but it only reads tags from 0.5cm distance or less. Is there a library maybe that would enable setting the gain of antenna? Or is there any other way to increase the reading range since theoretically this reader should be able to reader tags from 5-7cm distance.

**Comment by s-light** [comment]
what tags do you use?
if you use card-tags they tend to have a better range - as the antenna in theme is very big..

**Comment by Cincinnatu** [comment]
> 我最近购买了一台 Grove 125kHz 阅读器，但它只能读取 0.5 厘米或更短距离的标签。是否有可能允许设置天线增益的库？或者有没有其他方法可以增加阅读范围，因为理论上这个阅读器应该能够在 5-7 厘米的距离读取标签。

He is correct: https://github.com/Seeed-Studio/RFID_Library/issues/11#issuecomment-1127477866. The read range of low-frequency RFID is very short, and the actual range depends on factors such as the size of the tag and the material it is attached to.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
