### ISSUE TITLE
Using Grove - 125KHz RFID Reader V1.0 with M5Stack

### ISSUE THREAD

**Issue by jerome83136** [Seeed-Studio/RFID_Library#12]
Hello all,

I know there is little chance you help me on this; but let's try anyway :)

I try to use your reader with M5stack ["ExtPort"](https://docs.m5stack.com/en/module/extport_for_core2)

I verified the jumper was on "u" so it communicates on TTL (9600 baudrate, 8 data bits, 1 stop bit, and no verify bit)

I connected:
- TX to M5 ExtPort (Port C / PIN13)
- RX to M5 ExtPort (Port C / PIN14)

On [M5 UIFlow](https://community.m5stack.com/assets/uploads/files/1679067565138-9b0cde45-1a62-4fe4-866f-a0a6c3ccfc52-image.png) I tried to use UART to read the ID of some RFID tags

But I get no data from the reader.
Did I do something wrong ?

Thank you very much for your help
Best regards

**Comment by Cincinnatu** [comment]
Is the issue still present now? If it is, I will need you to provide more information for me to reproduce and resolve the issue.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
