### ISSUE TITLE
detecting but not reading RFID tag

### ISSUE THREAD

**Issue by CharlyAutomatico** [Seeed-Studio/RFID_Library#13]
Hi

I just receive "RFID Test.." message in my monitor serie of Arduino UNO (also with TEST and DEBUG on), the tag that I am using is the typical EM4100 125khz RFID Key (RFID Tag). I am sure that reader is working because when I  approach the tag key the green led lights, so, is detecting the RFID Tag but it doesn´t read it.

Is there anything I can do?
Do this RFID reader works only with cards?
Thank in advance

**Comment by Cincinnatu** [comment]
Is the issue still present now? If it is, I will need you to provide more information for me to reproduce and resolve the issue.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
