### ISSUE TITLE
Cannot Find "SoftwareSerial" Library for Arduino 

### ISSUE THREAD

**Issue by creepscompilation** [Seeed-Studio/RFID_Library#14]
Hello,

We purchased (3) of this GROVE 125KHZ RFID READER from DigiKey, installed this library, and we are
trying to simply run the example INO project, however, it requires another library, "SoftwareSerial.h"  and
we cannot find or download that library to resolve the compiler error below.

C:\Users\MB\AppData\Local\Temp\.arduinoIDE-unsaved2023513-7008-qedy82.cm54\RFID_UART\RFID_UART.ino:3:10: fatal error: SoftwareSerial.h: No such file or directory
 #include <SoftwareSerial.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Compilation error: SoftwareSerial.h: No such file or directory

**Comment by Cincinnatu** [comment]
SoftwareSerial is an official library file for Arduino. If you encounter the error "No such file or directory," you need to check your Arduino IDE.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
