### ISSUE TITLE
if(RFID.isAvailable()) is always false

### ISSUE THREAD

**Issue by mcousine** [Seeed-Studio/RFID_Library#2]
I use virgin tag bough from seeed the id is 0 if i put your SeeedRFID.cpp in DEBUG i see the Serial.println("SeeedRFID:read() function, and the RFID raw data: "); into the serial monitor fut never the 

Serial.print("RFID card number: "); in your example.ino ? 

Is it because i used non program rfid tag ?

**Comment by yexiaobo-seeedstudio** [comment]
The library only Support EM4100 compatible read only or read/write tags.
